version: '3'
services:
  mongo-db:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    networks:
      - exif-app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask-app:
    build:
      context: ../exif-app-backend
    container_name: exif-app-backend
    ports:
      - "5000:5000"
    networks:
      - exif-app-network
    depends_on:
      - mongo-db
    environment:
      MONGO_URI: "mongodb://mongodb:27017"

  react-app:
    build:
      context: ../exif-app-frontend
    container_name: exif-app-frontend
    ports:
      - "3000:3000"
    environment:
      FLASK_APP_URL: "exif-app-backend:5000"

networks:
  exif-app-network:

volumes:
  mongo_data:
